### ISSUE TITLE
grunt run and grunt package fail

### ISSUE THREAD

**Issue by ehartford** [TaylorBriggs/stripe-lambda#5] opened 2017-02-27 07:25 UTC
Failure!  Message:
------------------
{"type":"StripeInvalidRequestError","stack":"Error: Must provide source or customer.\n  at Constructor._Error

**Comment by TaylorBriggs** [comment] 2017-02-27 16:26
Sounds like you don't have the correct values set in your `.env` file. Make sure you have followed the [authentication step](https://github.com/TaylorBriggs/stripe-lambda#authentication) and insert your values from Stripe in the `.env` file.

**Comment by ehartford** [comment] 2017-02-27 18:11
from a clean git clone

    $ npm install

    $ cat .env
    STRIPE_SECRET_KEY=sk_live_blablabla
    AWS_ACCOUNT_ID=123456789012
    AWS_REGION=us-west-2
    AWS_FUNCTION_NAME=stripe
    RECEIPT_EMAIL=ehartford@gmail.com

    $ grunt run
    Running "build_event" task

    Running "lambda_invoke:default" (lambda_invoke) task


    Failure!  Message:
    ------------------
    {"type":"StripeInvalidRequestError","stack":"Error: Must provide source or customer.\n    at Constructor._Error

does your .env look different?

can you build it from a clean git clone?

What version of node / npm are you using?  

    $ node --version
    v7.4.0
    $ npm --version
    4.0.5
    $ grunt --version
    grunt-cli v1.2.0
    grunt v0.4.5

**Comment by TaylorBriggs** [comment] 2017-02-28 16:45
I'll do a bit of troubleshooting on this tonight. This function was written when Lambda only supported Node v0.10, and it hasn't been updated since AWS provided support for Node v4.3. I can't guarantee compatibility with Node v7.4.

**Comment by ehartford** [comment] 2017-02-28 22:11
Installed nvm,

Tried it with 4.3.  
Tried it with 0.10.48.  

wonder if maybe there's a version issue with stripe library itself

removed all the "^" from package.json to make sure I'm using the exact same versions you used - 
no luck.

**Comment by TaylorBriggs** [comment] 2017-03-01 05:02
What does your `event.json` look like? It should be something like:

```json
{
    "source": "tok_19sPUO4WjHqzrY2hsudwIhSY",
    "amount": 2000,
    "currency": "usd",
    "description": "test description",
    "receipt_email": "taylor.briggs.dev@gmail.com"
}
```

The error message coming back from the `lambda:invoke` task reads like there's no `source` provided. Perhaps try your test secret key and see if you get a success response? Maybe there's something you need to do with Stripe to activate the account to use the live key.

I haven't been able to reproduce the issue using Node 4.3.2, npm 2.14.2, grunt-cli 1.2.0, and grunt 0.4.5.

**Comment by mihirchronicles** [comment] 2017-05-23 20:57
Getting the same error - "type":"StripeInvalidRequestError","stack":"Error: Must provide source or customer.

**Comment by TaylorBriggs** [comment] 2017-05-23 21:18
@mihirchronicles the error message reads like the `source` was not provided. See my comment above from Feb 28. I'm going to close this issue as there are not clear steps to reproduce and the error is caused by either a misconfiguration on the server side, or failure to provide the `source` or `customer` when invoking the Lambda function as the error message indicates.

Here's what I've been able to find on the Stripe side:
https://github.com/stripe/stripe-node/issues/307

**Closed as completed by TaylorBriggs** 2017-05-23 21:18 UTC
